apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  selector:
    matchLabels:
      io.kompose.service: backend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - name: backend
          image: ACCT.dkr.ecr.REG.amazonaws.com/REPO:VER
          env:
          - name: MYSQL_USER
            value: "MYSQL_USER_VALUE"
          - name: MYSQL_PASSWORD
            value: "MYSQL_PASSWORD_VALUE"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_HOST
            value: "versus.c7pmwjifbb9j.us-east-2.rds.amazonaws.com"
          - name: MYSQL_DATABASE
            value: "versus"
          ports:
          - containerPort: 8080
          resources: {}
      restartPolicy: Always
